export type KnockoutScheduleItem = {
  matchId: string
  stage: 'roundOf32' | 'roundOf16' | 'quarterFinals' | 'semiFinals' | 'thirdPlace' | 'final'
  dateIso: string
  localTime: string
  venueCity:
    | 'Los Angeles'
    | 'Boston'
    | 'Monterrey'
    | 'Houston'
    | 'New York/New Jersey'
    | 'Dallas'
    | 'Mexico City'
    | 'Atlanta'
    | 'San Francisco Bay Area'
    | 'Seattle'
    | 'Toronto'
    | 'Vancouver'
    | 'Miami'
    | 'Kansas City'
    | 'Philadelphia'
  stadium: string
  sourceNote: string
}

export const knockoutScheduleByMatchId: Record<string, KnockoutScheduleItem> = {
  '73': {
    matchId: '73',
    stage: 'roundOf32',
    dateIso: '2026-06-28',
    localTime: '12:00',
    venueCity: 'Los Angeles',
    stadium: 'Los Angeles Stadium',
    sourceNote: 'Official FIFA hospitality listing and FIFA match-centre search result.',
  },
  '74': {
    matchId: '74',
    stage: 'roundOf32',
    dateIso: '2026-06-29',
    localTime: '16:30',
    venueCity: 'Boston',
    stadium: 'Boston Stadium',
    sourceNote: 'Official FIFA hospitality listing.',
  },
  '75': {
    matchId: '75',
    stage: 'roundOf32',
    dateIso: '2026-06-29',
    localTime: '19:00',
    venueCity: 'Monterrey',
    stadium: 'Monterrey Stadium',
    sourceNote: 'Official FIFA hospitality listing.',
  },
  '76': {
    matchId: '76',
    stage: 'roundOf32',
    dateIso: '2026-06-29',
    localTime: '16:00',
    venueCity: 'Houston',
    stadium: 'Houston Stadium',
    sourceNote: 'Official FIFA hospitality listing and FIFA match-centre search result.',
  },
  '77': {
    matchId: '77',
    stage: 'roundOf32',
    dateIso: '2026-06-30',
    localTime: '16:00',
    venueCity: 'New York/New Jersey',
    stadium: 'New York/New Jersey Stadium',
    sourceNote: 'Official FIFA hospitality listing.',
  },
  '78': {
    matchId: '78',
    stage: 'roundOf32',
    dateIso: '2026-06-30',
    localTime: '16:00',
    venueCity: 'Dallas',
    stadium: 'Dallas Stadium',
    sourceNote: 'Official FIFA hospitality listing and FIFA match-centre search result.',
  },
  '79': {
    matchId: '79',
    stage: 'roundOf32',
    dateIso: '2026-06-30',
    localTime: '19:00',
    venueCity: 'Mexico City',
    stadium: 'Mexico City Stadium',
    sourceNote: 'Official FIFA hospitality listing.',
  },
  '80': {
    matchId: '80',
    stage: 'roundOf32',
    dateIso: '2026-07-01',
    localTime: '16:00',
    venueCity: 'Atlanta',
    stadium: 'Atlanta Stadium',
    sourceNote: 'Official FIFA hospitality listing and FIFA match-centre search result.',
  },
  '81': {
    matchId: '81',
    stage: 'roundOf32',
    dateIso: '2026-07-01',
    localTime: '17:00',
    venueCity: 'San Francisco Bay Area',
    stadium: 'San Francisco Bay Area Stadium',
    sourceNote: 'Official FIFA hospitality listing.',
  },
  '82': {
    matchId: '82',
    stage: 'roundOf32',
    dateIso: '2026-07-01',
    localTime: '20:00',
    venueCity: 'Seattle',
    stadium: 'Seattle Stadium',
    sourceNote: 'Official FIFA hospitality listing and FIFA match-centre search result.',
  },
  '83': {
    matchId: '83',
    stage: 'roundOf32',
    dateIso: '2026-07-02',
    localTime: '16:00',
    venueCity: 'Toronto',
    stadium: 'Toronto Stadium',
    sourceNote: 'Official FIFA hospitality listing and FIFA match-centre search result.',
  },
  '84': {
    matchId: '84',
    stage: 'roundOf32',
    dateIso: '2026-07-02',
    localTime: '16:00',
    venueCity: 'Los Angeles',
    stadium: 'Los Angeles Stadium',
    sourceNote: 'Official FIFA hospitality listing and FIFA match-centre search result.',
  },
  '85': {
    matchId: '85',
    stage: 'roundOf32',
    dateIso: '2026-07-02',
    localTime: '20:00',
    venueCity: 'Vancouver',
    stadium: 'BC Place Vancouver',
    sourceNote: 'Official FIFA hospitality listing.',
  },
  '86': {
    matchId: '86',
    stage: 'roundOf32',
    dateIso: '2026-07-03',
    localTime: '18:00',
    venueCity: 'Miami',
    stadium: 'Miami Stadium',
    sourceNote: 'Official FIFA hospitality listing.',
  },
  '87': {
    matchId: '87',
    stage: 'roundOf32',
    dateIso: '2026-07-03',
    localTime: '20:30',
    venueCity: 'Kansas City',
    stadium: 'Kansas City Stadium',
    sourceNote: 'Official FIFA hospitality listing.',
  },
  '88': {
    matchId: '88',
    stage: 'roundOf32',
    dateIso: '2026-07-03',
    localTime: '13:00',
    venueCity: 'Dallas',
    stadium: 'Dallas Stadium',
    sourceNote: 'Official FIFA hospitality listing.',
  },
  '89': {
    matchId: '89',
    stage: 'roundOf16',
    dateIso: '2026-07-04',
    localTime: '17:00',
    venueCity: 'Philadelphia',
    stadium: 'Philadelphia Stadium',
    sourceNote: 'Official FIFA hospitality listing.',
  },
  '90': {
    matchId: '90',
    stage: 'roundOf16',
    dateIso: '2026-07-04',
    localTime: '12:00',
    venueCity: 'Houston',
    stadium: 'Houston Stadium',
    sourceNote: 'Official FIFA hospitality listing.',
  },
  '91': {
    matchId: '91',
    stage: 'roundOf16',
    dateIso: '2026-07-05',
    localTime: '16:00',
    venueCity: 'New York/New Jersey',
    stadium: 'New York/New Jersey Stadium',
    sourceNote: 'Official FIFA hospitality listing.',
  },
  '92': {
    matchId: '92',
    stage: 'roundOf16',
    dateIso: '2026-07-05',
    localTime: '18:00',
    venueCity: 'Mexico City',
    stadium: 'Mexico City Stadium',
    sourceNote: 'Official FIFA hospitality listing.',
  },
  '93': {
    matchId: '93',
    stage: 'roundOf16',
    dateIso: '2026-07-06',
    localTime: '14:00',
    venueCity: 'Dallas',
    stadium: 'Dallas Stadium',
    sourceNote: 'Official FIFA hospitality listing.',
  },
  '94': {
    matchId: '94',
    stage: 'roundOf16',
    dateIso: '2026-07-06',
    localTime: '17:00',
    venueCity: 'Seattle',
    stadium: 'Seattle Stadium',
    sourceNote: 'Official FIFA hospitality listing.',
  },
  '95': {
    matchId: '95',
    stage: 'roundOf16',
    dateIso: '2026-07-07',
    localTime: '12:00',
    venueCity: 'Atlanta',
    stadium: 'Atlanta Stadium',
    sourceNote: 'Official FIFA hospitality listing.',
  },
  '96': {
    matchId: '96',
    stage: 'roundOf16',
    dateIso: '2026-07-07',
    localTime: '13:00',
    venueCity: 'Vancouver',
    stadium: 'BC Place Vancouver',
    sourceNote: 'Official FIFA hospitality listing.',
  },
  '97': {
    matchId: '97',
    stage: 'quarterFinals',
    dateIso: '2026-07-09',
    localTime: '16:00',
    venueCity: 'Boston',
    stadium: 'Boston Stadium',
    sourceNote: 'Official FIFA hospitality listing.',
  },
  '98': {
    matchId: '98',
    stage: 'quarterFinals',
    dateIso: '2026-07-10',
    localTime: '12:00',
    venueCity: 'Los Angeles',
    stadium: 'Los Angeles Stadium',
    sourceNote: 'Official FIFA hospitality listing.',
  },
  '99': {
    matchId: '99',
    stage: 'quarterFinals',
    dateIso: '2026-07-11',
    localTime: '17:00',
    venueCity: 'Miami',
    stadium: 'Miami Stadium',
    sourceNote: 'Official FIFA hospitality listing.',
  },
  '100': {
    matchId: '100',
    stage: 'quarterFinals',
    dateIso: '2026-07-11',
    localTime: '20:00',
    venueCity: 'Kansas City',
    stadium: 'Kansas City Stadium',
    sourceNote: 'Official FIFA hospitality listing.',
  },
  '101': {
    matchId: '101',
    stage: 'semiFinals',
    dateIso: '2026-07-14',
    localTime: '14:00',
    venueCity: 'Dallas',
    stadium: 'Dallas Stadium',
    sourceNote: 'Official FIFA hospitality listing.',
  },
  '102': {
    matchId: '102',
    stage: 'semiFinals',
    dateIso: '2026-07-15',
    localTime: '15:00',
    venueCity: 'Atlanta',
    stadium: 'Atlanta Stadium',
    sourceNote: 'Official FIFA hospitality listing.',
  },
  '103': {
    matchId: '103',
    stage: 'thirdPlace',
    dateIso: '2026-07-18',
    localTime: '17:00',
    venueCity: 'Miami',
    stadium: 'Miami Stadium',
    sourceNote: 'Official FIFA hospitality listing.',
  },
  '104': {
    matchId: '104',
    stage: 'final',
    dateIso: '2026-07-19',
    localTime: '15:00',
    venueCity: 'New York/New Jersey',
    stadium: 'New York/New Jersey Stadium',
    sourceNote: 'Official FIFA hospitality listing.',
  },
}
